### ISSUE TITLE
Preferences > Path to * Binary are folder selections on Windows

### ISSUE THREAD

**Issue by tarocco** [apaeffgen/PanConvert#2]
Expected behavior: clicking on [...] allows me to select the pandoc or multimarkdown executable
Observed behavior: folder selection dialog is presented with no option to select a .exe (or optionally files with any extension with the combo box thing Windows has for file select dialogs)
i.e. I have to append pandoc.exe to the path in the preferences window manually.

Probably not ideal, but this is another possibility:
Expected behavior (alt): clicking on [...] allows me to select the directory containing pandoc or multimarkdown executables
Observed behavior (alt): folder selection completes and program fails to look for presence of executable files in those directories

I'm all for specifying the executable path, not its directory, since that would make more sense.

Using PanConvert 0.1.5 on Windows 10 x64 [from SourceForge](https://sourceforge.net/projects/panconvert/files/Newest/PanConvert-0.1.5-win32.msi/download)

**Comment by apaeffgen** [comment]
Did you use the binary file or the source-code?
regards Andreas

**Comment by apaeffgen** [comment]
I suspect the binary is compiled on a 32 bit system. Could you check the source-code version?

**Comment by tarocco** [comment]
I will check when I have time to set up pyqt
