### ISSUE TITLE
Html > markdown2html results in markdown2latex

### ISSUE THREAD

**Issue by tarocco** [apaeffgen/PanConvert#3]
Expected behavior: select markdown2html from the menu and it converts the markdown into html
Observed behavior: instead, it converts markdown into LaTeX.

Using PanConvert 0.1.5 on Windows 10 x64 [from SourceForge](https://sourceforge.net/projects/panconvert/files/Newest/PanConvert-0.1.5-win32.msi/download)

**Comment by apaeffgen** [comment]
> Using PanConvert 0.1.5 on Windows 10 x64 from SourceForge https://sourceforge.net/projects/panconvert/files/Newest/PanConvert-0.1.5-win32.msi/download

Did you use the binary file or the source-code?
regards Andreas

**Comment by apaeffgen** [comment]
I suspect the binary is compiled on a 32 bit system. Could you check the source-code version?
