### ISSUE TITLE
msi file deads without errors in win8.1 v6.3

### ISSUE THREAD

**Issue by netalex** [apaeffgen/PanConvert#4]
launching pandoc-1.19.1-windows.msi file exits immediately whitout effects.

**Comment by apaeffgen** [comment]
If it is pandoc-1.19.1-windows.msi, you should get help from pandoc, not from Panconvert.
Panconvert is just a wrapper, that uses a successfully installed pandoc version

**Comment by apaeffgen** [comment]
If you can not install the newest version of Panconvert, try older versions

**Comment by apaeffgen** [comment]
The same with pandoc. Try install older versions.
The binary or Panconvert does not work properly on 64bit Windows. You have to use the source version

**Comment by netalex** [comment]
i'm sorry wrog filename copypasted. I was meaning PanConvert-0.2.0-win32.msi

**Comment by apaeffgen** [comment]
Please provide a little bit more detail:
Windows 8.1 32bit or 64bit? Panconvert is compiled on Win10-32bit

**Comment by apaeffgen** [comment]
It will probably not work on 64-bit Windows Systems

**Comment by netalex** [comment]
@apaeffgen it's 64bit

**Comment by apaeffgen** [comment]
Your best option is use to use the source code. 64bit binaries are not supported on windows yet.
Be aware that all the links to python, pyqt5 and qt5 are 32 bit in the documentation. Use google to find all the necessary 64bit tools.
