### ISSUE TITLE
The binary file for windows were flagged as containging a .exe virusby McAffe

### ISSUE THREAD

**Issue by jermon** [apaeffgen/PanConvert#6]
The binary file for windows were flagged as containging a .exe virusby McAffe
pandoc-2.2.3.2-windows-x86_64.msi

**Comment by apaeffgen** [comment]
Pandoc is not Panconvert. Did you confuse the programs?

**Comment by jermon** [comment]
Sorry.
Panconvert-0.2.7-windows-installer.exe were flagged as containging a .exe virusby McAffe

**Comment by apaeffgen** [comment]
Did you download it from 
https://sourceforge.net/projects/panconvert/files/Newest/Panconvert-0.2.7-windows-installer.exe/download

If so, I checked it with Avast.It found no Virus. Some Virus checkers have false positives. Please send the file with a report to MacAfee. Maybe they can explain, what is going on.

Panconvert uses the QT5 Framework and the PyQT5 Middleware. Maybe some of these files are recognized as a Virus. If you look at the code, there is nothing malicious in the source code.
I can not guaranty that in the framework there is a virus. But it is checked with Avast and Microsoft Security Essentials. They did not find anything.
