### ISSUE TITLE
can you support more format?

### ISSUE THREAD

**Issue by longlu** [apaeffgen/PanConvert#7]
orgmode
mediawiki
tiddywiki
etc, 

that would be very useful

**Comment by apaeffgen** [comment]
All pandoc formats are supported. Depending on the pandoc version you have installed, you need to compile panconvert on your own.

Bundling the binaries with the new version of qt5.x made some problems. 
You need to use the manual mode. There you can use all the pandoc formats.
Hope that helps

**Comment by longlu** [comment]
i simply cloned the github source, and then run python Panconvert.py,and the program is running
it seems that I don't need to install anything.
