### ISSUE TITLE
Fails to start Qt5.14.2: local variable referenced before assignment

### ISSUE THREAD

**Issue by alan1world** [apaeffgen/PanConvert#8]
Traceback (most recent call last):
  File "Panconvert.py", line 65, in <module>
    main()
  File "Panconvert.py", line 31, in main
    myapp = StartQT5()
  File "Apps/git/panconvert/source/main_gui.py", line 976, in __init__
    self.ui.StandardConversion.setChecked(strtobool(Standard_Conversion))
UnboundLocalError: local variable 'Standard_Conversion' referenced before assignment

**Comment by apaeffgen** [comment]
Unfortunately PyQT5 Versions are not upward / downward compatible. You may have luck with a non-tested version, but do not expect to much. I testet it wit 5.7 up to 5.11. The original source code was written in 5.3 and broke for some changes in 5.4. So unfortunately you have to stick with a certain version of QT5 and PyQT.

**Comment by alan1world** [comment]
I don't need this myself anymore, but in case anyone else needs it here is the answer.

If you add a reference to the missing variable, then it works perfectly.

I added `Standard_Conversion = "true"` to line 956 (just before `Batch_Conversion = settings.value('Batch_Conversion', False)` ).

**Comment by apaeffgen** [comment]
Thanks for the hint. I will look in to it. BTW, why you dont need it any more? Do you use another program? Or you corrected the errors?

**Comment by alan1world** [comment]
I call pandoc directly either on the command line or via a python script without a GUI. When pandoc dropped the `--smart` flag, it was painful.
