### ISSUE TITLE
Can I help in order to propose a french interface ? 

### ISSUE THREAD

**Issue by Thibaut-Kovaltchouk** [apaeffgen/PanConvert#9]
I don't know how you want to work, but I can translate to french. I found this project very usefull.

**Comment by apaeffgen** [comment]
Hi Thibaut (is it the first part of your last name?)
every help is welcome.
I use the integrated qt translation system. With a mo file editor you can duplicate an existing mo file and use this for the french translation.
Afterwards you can use github to provide the file. 
Or can send it via email.

Hope that explains a bit of the process

**Comment by Thibaut-Kovaltchouk** [comment]
Finally, I made a pull request in order to propose few ameliorations that I had to made in order to test my files. (and Thibaut is my first name, Kovaltchouk is my last name).

**Comment by apaeffgen** [comment]
Thanks for the translation. 
I had to fix one glitch for my environment to make your code work. I updated the repository. Your code is integrated now.
